// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalTechBrief.Infrastructure.Persistence;

#nullable disable

namespace PersonalTechBrief.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PersonalTechBriefDbContext))]
    [Migration("20260914221316_AddBriefs")]
    partial class AddBriefs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonalTechBrief.Domain.Analysis.TechnologyUpdate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<double>("CurrentRelevanceScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("FirstObservedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastObservedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PrimaryTopic")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RepresentativeTitle")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LastObservedAtUtc")
                        .HasDatabaseName("IX_TechnologyUpdates_LastObservedAtUtc");

                    b.HasIndex("PrimaryTopic", "LastObservedAtUtc")
                        .HasDatabaseName("IX_TechnologyUpdates_PrimaryTopic_LastObservedAtUtc");

                    b.ToTable("TechnologyUpdates", (string)null);
                });

            modelBuilder.Entity("PersonalTechBrief.Domain.Analysis.TechnologyUpdateSource", b =>
                {
                    b.Property<Guid>("TechnologyUpdateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LinkedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<double?>("SimilarityScore")
                        .HasColumnType("float");

                    b.HasKey("TechnologyUpdateId", "SourceItemId");

                    b.HasIndex("SourceItemId")
                        .IsUnique()
                        .HasDatabaseName("UX_TechnologyUpdateSources_SourceItemId");

                    b.ToTable("TechnologyUpdateSources", (string)null);
                });

            modelBuilder.Entity("PersonalTechBrief.Domain.Analysis.UpdateInterestMatch", b =>
                {
                    b.Property<Guid>("TechnologyUpdateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InterestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("MatchStrength")
                        .HasColumnType("float");

                    b.Property<DateTime>("MatchedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("TechnologyUpdateId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("UpdateInterestMatches", (string)null);
                });

            modelBuilder.Entity("PersonalTechBrief.Domain.Briefs.Brief", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CandidateCount")
                        .HasColumnType("int");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GenerationVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("SelectedCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("WindowEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WindowStartUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedAtUtc")
                        .HasDatabaseName("IX_Briefs_GeneratedAtUtc");

                    b.ToTable("Briefs", (string)null);
                });

            modelBuilder.Entity("PersonalTechBrief.Domain.Briefs.BriefItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BriefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModelOrAlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<double>("RelevanceScoreSnapshot")
                        .HasColumnType("float");

                    b.Property<string>("SummarySnapshot")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("TechnologyUpdateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TitleSnapshot")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("TopicSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("WhyRelevantSnapshot")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("TechnologyUpdateId");

                    b.HasIndex("BriefId", "Rank")
                        .IsUnique()
                        .HasDatabaseName("UX_BriefItems_BriefId_Rank");

                    b.HasIndex("BriefId", "TechnologyUpdateId")
                        .IsUnique()
                        .HasDatabaseName("UX_BriefItems_BriefId_TechnologyUpdateId");

                    b.ToTable("BriefItems", (string)null);
                });

            modelBuilder.Entity("PersonalTechBrief.Domain.Briefs.BriefItemSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BriefItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SourceItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TitleSnapshot")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UrlSnapshot")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("BriefItemId")
                        .HasDatabaseName("IX_BriefItemSources_BriefItemId");

                    b.HasIndex("SourceItemId");

                    b.ToTable("BriefItemSources", (string)null);
                });

            modelBuilder.Entity("PersonalTechBrief.Domain.Ingestion.IngestionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ErrorDetail")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("NewItemCount")
                        .HasColumnType("int");

                    b.Property<int>("RetrievedItemCount")
                        .HasColumnType("int");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "StartedAtUtc")
                        .HasDatabaseName("IX_IngestionRuns_SourceId_StartedAtUtc");

                    b.ToTable("IngestionRuns", (string)null);
                });

            modelBuilder.Entity("PersonalTechBrief.Domain.Ingestion.SourceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CanonicalUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Excerpt")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<int>("FailureCount")
                        .HasColumnType("int");

                    b.Property<string>("LastFailureCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("NormalizedUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("NormalizedUrlHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("OriginType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("OriginalUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RetrievedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("IX_SourceItems_ContentHash")
                        .HasFilter("[ContentHash] IS NOT NULL");

                    b.HasIndex("NormalizedUrlHash")
                        .HasDatabaseName("IX_SourceItems_NormalizedUrlHash")
                        .HasFilter("[NormalizedUrlHash] IS NOT NULL");

                    b.HasIndex("NormalizedTitle", "RetrievedAtUtc")
                        .HasDatabaseName("IX_SourceItems_NormalizedTitle_RetrievedAtUtc");

                    b.HasIndex("SourceId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("UX_SourceItems_SourceId_ExternalId")
                        .HasFilter("[SourceId] IS NOT NULL AND [ExternalId] IS NOT NULL");

                    b.ToTable("SourceItems", (string)null);
                });

            modelBuilder.Entity("PersonalTechBrief.Domain.Interests.Interest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("UX_Interests_NormalizedName_Active")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("Interests", (string)null);
                });

            modelBuilder.Entity("PersonalTechBrief.Domain.Messaging.ContentProcessingInboxReceipt", b =>
                {
                    b.Property<Guid>("SourceItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EnvelopeJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("SourceItemId");

                    b.HasIndex("Status", "ReceivedAtUtc", "SourceItemId");

                    b.ToTable("ContentProcessingInbox", (string)null);
                });

            modelBuilder.Entity("PersonalTechBrief.Domain.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("DispatchAttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DispatchedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IngestionRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastDispatchAttemptAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastDispatchError")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("IngestionRunId");

                    b.HasIndex("SourceId");

                    b.HasIndex("SourceItemId")
                        .IsUnique()
                        .HasDatabaseName("UX_OutboxMessages_SourceItemId");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("IX_OutboxMessages_Status_CreatedAtUtc");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("PersonalTechBrief.Domain.Sources.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ETag")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("FeedUrl")
                        .IsRequired()
                        .HasMaxLength(850)
                        .HasColumnType("nvarchar(850)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastIngestionAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastIngestionStatus")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedFeedUrl")
                        .IsRequired()
                        .HasMaxLength(850)
                        .HasColumnType("nvarchar(850)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedFeedUrl")
                        .IsUnique()
                        .HasDatabaseName("UX_Sources_NormalizedFeedUrl_Enabled")
                        .HasFilter("[IsEnabled] = 1");

                    b.ToTable("Sources", (string)null);
                });

            modelBuilder.Entity("PersonalTechBrief.Domain.Analysis.TechnologyUpdateSource", b =>
                {
                    b.HasOne("PersonalTechBrief.Domain.Ingestion.SourceItem", null)
                        .WithMany()
                        .HasForeignKey("SourceItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalTechBrief.Domain.Analysis.TechnologyUpdate", null)
                        .WithMany()
                        .HasForeignKey("TechnologyUpdateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalTechBrief.Domain.Analysis.UpdateInterestMatch", b =>
                {
                    b.HasOne("PersonalTechBrief.Domain.Interests.Interest", null)
                        .WithMany()
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalTechBrief.Domain.Analysis.TechnologyUpdate", null)
                        .WithMany()
                        .HasForeignKey("TechnologyUpdateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalTechBrief.Domain.Briefs.BriefItem", b =>
                {
                    b.HasOne("PersonalTechBrief.Domain.Briefs.Brief", null)
                        .WithMany("Items")
                        .HasForeignKey("BriefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalTechBrief.Domain.Analysis.TechnologyUpdate", null)
                        .WithMany()
                        .HasForeignKey("TechnologyUpdateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalTechBrief.Domain.Briefs.BriefItemSource", b =>
                {
                    b.HasOne("PersonalTechBrief.Domain.Briefs.BriefItem", null)
                        .WithMany("Sources")
                        .HasForeignKey("BriefItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalTechBrief.Domain.Ingestion.SourceItem", null)
                        .WithMany()
                        .HasForeignKey("SourceItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalTechBrief.Domain.Ingestion.IngestionRun", b =>
                {
                    b.HasOne("PersonalTechBrief.Domain.Sources.Source", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalTechBrief.Domain.Ingestion.SourceItem", b =>
                {
                    b.HasOne("PersonalTechBrief.Domain.Sources.Source", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PersonalTechBrief.Domain.Messaging.ContentProcessingInboxReceipt", b =>
                {
                    b.HasOne("PersonalTechBrief.Domain.Ingestion.SourceItem", null)
                        .WithMany()
                        .HasForeignKey("SourceItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalTechBrief.Domain.Messaging.OutboxMessage", b =>
                {
                    b.HasOne("PersonalTechBrief.Domain.Ingestion.IngestionRun", null)
                        .WithMany()
                        .HasForeignKey("IngestionRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalTechBrief.Domain.Sources.Source", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalTechBrief.Domain.Ingestion.SourceItem", null)
                        .WithMany()
                        .HasForeignKey("SourceItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalTechBrief.Domain.Briefs.Brief", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PersonalTechBrief.Domain.Briefs.BriefItem", b =>
                {
                    b.Navigation("Sources");
                });
#pragma warning restore 612, 618
        }
    }
}
